::Created by HTSoft Studios - Read the file "copyright.txt" for more info. (Do not distribute)
::(Use "NotePadPP" or anything other than "Notepad" to view better this file)
:: Languages used:    98% Batch    2% VBScript
::_______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______
::______//_____//_____//_____//_____//_____//_____//_____//_____//_____//_____//______ \
::     _    _   _______    _____      _____   _                 _   _                 | |
::    | |  | | |__   __|  / ____|    / ____| | |               | | (_)                | |
::    | |__| |    | |    | (___     | (___   | |_   _   _    __| |  _    ___    ___   | |
::    |  __  |    | |     \___ \     \___ \  | __| | | | |  / _` | | |  / _ \  / __|  | |
::    | |  | |    | |     ____) |    ____) | | |_  | |_| | | (_| | | | | (_) | \__ \  | |
::    |_|  |_|    |_|    |_____/    |_____/   \__|  \__,_|  \__,_| |_|  \___/  |___/  | |
::_______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______| |
::______//_____//_____//_____//_____//_____//_____//_____//_____//_____//_____//______ /
::
:: (!) DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING - EDITING ANYTHING IN HERE MAY CAUSE MISS BEHAVIOR AND CAUSE PROBLEMS
::     TO YOUR COMPUTER (!)
:: (!) IF ANYONE TOLD YOU TO COPY AND PASTE CODE IN HERE OR DOWNLOAD ADDITIONAL FILES, THEY ARE MOST LIKELY TRYING TO SCAM YOU,
::     UNLESS THE OFFICIAL HTS DEVELOPERS TOLD YOU TO DO SO (!)
:LAUNCHER
@ECHO OFF
@CHCP 65001>NUL
@TITLE Battles of Batch
@PUSHD "%CD%"
@PROMPT !^>
@VERIFY OFF
ECHO. Setting up ...
FOR /F "TOKENS=4-5 DELIMS= " %%I IN ('VER') DO SET WINVER=%%I
IF NOT "%WINVER:~0,3%" == "10." IF NOT "%WINVER:~0,3%" == "11." (
	CLS
	ECHO.You are NOT running a supported OS or OS Version. Upgrade/Change your OS to Windows 10 or 11!
	PAUSE>NUL
	EXIT
)
:: Check if logs folder exist,
IF NOT EXIST .\data\logs MD ".\data\logs"
::  start the logger and check if accessible,
2>>".\data\logs\errors.txt" ( SET "STARTED=1"&CALL :STARTUP-COMPLETE )
::   if not accessible then exit, else below command will be skipped.
@IF /I NOT DEFINED STARTED EXIT 1
:STARTUP-COMPLETE
IF NOT EXIST "%~n0%~x0" (
	CLS
	ECHO.ERROR Denied Directory.
	ECHO.
	ECHO.Make sure the following:
	ECHO.1. The program isn't running in a zip file or any winrar format.
	ECHO.2. The program has permissions to add files on the current directory.
	ECHO.3. Don't launch it directly from a search bar or a run-in, it breaks the directory.
	ECHO.4. If you are using a shortcut, make sure you added the correct directory.
	ECHO.5. Do not run with administrator/elevated permissions.
	ECHO.
	ECHO.If none of the above helped, contact us.
	PAUSE>NUL
	EXIT /B
) ELSE IF NOT EXIST "%CD%" (
	CLS
	ECHO.ERROR Abnormal Directory.
	ECHO.
	ECHO.Try the following:
	ECHO.1. Move the game, the whole folder, to a different location.
	ECHO.2. Make sure the directory's URL name includes ONLY latin characters.
	ECHO.3. Do not move it to shared folders, like Onedrive.
	ECHO.
	ECHO.If none of the above helped, contact us.
	PAUSE>NUL&EXIT
)
:RESTART
COLOR 0F
::VAR:-Variables
SET "DM=%CD%"
SET "DATA=%CD%\data"
SET "DATA_TMP=%DATA%\temp"
SET "DATA_IMAGES=%DATA%\images"
SET "DATA_SCRIPTS=%DATA%\scripts"
CALL "%DATA_SCRIPTS%\versions.cmd" || CALL :ERROR ERRLINE ID0001    0
:: Detect Errors
IF NOT DEFINED VERCODE CALL :ERROR ERRLINE ID0001A    0
IF NOT DEFINED VERS CALL :ERROR ERRLINE ID0001B    0
IF NOT DEFINED VERTYPE CALL :ERROR ERRLINE ID0001C    0
IF NOT DEFINED VERCOD.AUDIO_MANAGER CALL :ERROR ERRLINE ID0001D    0
IF NOT EXIST "%DATA_TMP%" MD "%DATA_TMP%"
SET "HTS_DATA=%APPDATA%\HTS_DATA"
SET "MAIN_GAME=%HTS_DATA%\BATTLESOFBATCH-%VERTYPE%-%VERCODE%"
SET "DATA_SAVES=%MAIN_GAME%\SAVES"
SET "DATA_SETTINGS=%MAIN_GAME%\SETTINGS"
SET "HTSANI=%DATA_SCRIPTS%\htsani.cmd"
SET "WAIT=%DATA_SCRIPTS%\wait.vbs"
SET "TITLE=Battles of Batch - "
SET LICENSE=copyright.txt
SET "PLAYERDATA.MONEY=%DATA_SCRIPTS%\playerdata\money.cmd"
SET "PLAYERDATA.XP=%DATA_SCRIPTS%\playerdata\xp.cmd"
SET "PLAYERDATA.LVL=%DATA_SCRIPTS%\playerdata\lvl.cmd"
SET "PLAYERDATA.LOAD=%DATA_SAVES%\PLAYERDATA.cmd"
SET "PLAYERSKILLS.LOAD=%DATA_SAVES%\SKILLS.cmd"
SET "SYS.LVL=%DATA_SCRIPTS%\playerdata\sys.lvl"
SET "UPDATER=%DATA_SCRIPTS%\updater.cmd"
SET "SAVE=%DATA_SCRIPTS%\save.cmd"
SET "DEBUG.GAMELOADER=%DATA_SCRIPTS%\debug"
SET "SHOP.TAB=ITEMS"
SET "SCRIPTS_POP=%DATA_SCRIPTS%\pop"
SET "INPUT_PART=nul"
SET "SELF_INPUT="
::VAR:-Settings
SET "SETTINGS.LOAD=%DATA_SETTINGS%\settings.cmd"
SET "TOGGLE.SOUNDS=%DATA_SCRIPTS%\settings\audio.cmd"
SET "SET.VOLUME=%DATA_SCRIPTS%\settings\volume.cmd"
SET "TOGGLE.UPDATES=%DATA_SCRIPTS%\settings\update.cmd"
SET "TOGGLE.SHORTCUTS=%DATA_SCRIPTS%\settings\shortcuts.cmd"
SET IGNORE_ERRORS=FALSE
::VAR:-Shortcut
SET TARGET=BattlesOfBatch
::VAR:-Cleanup
SET OLD.PLAYER.LVL=
SET HTS_DIR_ERR=
SET UDERFINE=
SET GAME.STATUS=NUL
SET RAINBOWMODE=
::VAR:-Player Stats
SET PLAYER.XP=0
SET PLAYER.XP.REQ=25
SET PLAYER.LVL=0
SET PLAYER.MAP.LEVEL=1
SET PLAYER.ITEM.BOMB=0
SET PLAYER.ITEM.HEAL=0
SET PLAYER.ITEM.UNKNOWN=
SET PLAYER.MONEY=0
SET CRIT.RATE=4
SET CRIT.STRE=60
SET "SEL.CHARACTER=SIMPSONS"
::VAR:-Shop
SET SHOP.PRICE.HEAL=10
SET SHOP.MAX.HEAL=400
SET SHOP.LVLREQ.HEAL=1
SET SHOP.PRICE.BOMB=100
SET SHOP.LVLREQ.BOMB=4
SET SHOP.MAX.BOMB=250
SET "SHOP.HEAL=%DATA_SCRIPTS%\shop\heal.cmd"
SET "SHOP.BOMB=%DATA_SCRIPTS%\shop\bomb.cmd"
::VAR:-Audio
SET /A "VOLUME.BATTLE=100*VOLUME/100*50"
SET /A "VOLUME.BATTLE=%VOLUME%-%VOLUME.BATTLE%/100"
SET "NOAUDIO=NUL"
SET "DATA_AUD=%DATA%\audio"
SET "DATA_AUD_S=%DATA_AUD%\system"
SET "DATA_AUDIO_G=%DATA_AUD%\game"
SET "DATA_AUDIO_G_P=%DATA_AUDIO_G%\player"
SET "DATA_AUDIO_G_B=%DATA_AUDIO_G%\battle"
SET "DATA_AUDIO_G_P_SUB=%DATA_AUDIO_G_P%\substat"
SET "DATA_AUDIO_G_P_ATK=%DATA_AUDIO_G_P%\attack"
SET "SFX.ATK=%DATA_AUDIO_G_P_ATK%\swing_"
SET "SFX.ATK.CRIT=%DATA_AUDIO_G_P_ATK%\crit_"
SET "SFX.ATK.MISS=%DATA_AUDIO_G_P_ATK%\miss_"
SET "SFX.BOMB=%DATA_AUDIO_G_P_SUB%\bomb"
SET "SFX.LASER=%DATA_AUDIO_G_P_SUB%\laser"
SET "DATA_AUDIO_SYS=%CD%\data\audio\sys"
SET "DATA_AUDIO_SYS_MENU=%CD%\data\audio\sys\menu"
SET "DATA_TMP_A=%DATA_TMP%\TMP_AUDIO.vbs"
SET "AudioManager=%DATA_SCRIPTS%\AudioManager.bat"
SET "ADirector=wscript.exe"
SET "AUD.MENU=%DATA_AUD_S%\menu.mp3"
SET "AUD.BATTLE.NORMAL=%DATA_AUDIO_G_B%\battle_normal.mp3"
SET "AUD.BATTLE.BOSS=%DATA_AUDIO_G_B%\battle_bossfight.mp3"
SET "MENU.AUDIO=%DATA_SCRIPTS%\menuaudio.cmd"
::VAR:-Layout
SET "COLS=117"
SET "LINES=48"
::VAR:-Interface
SET "INTERFACE=%DATA_SCRIPTS%\interface"
SET "STAT.MONEY=%INTERFACE%\money.cmd"
SET "STAT.XP=%INTERFACE%\xp.cmd"
SET "STAT.MAP=%INTERFACE%\map.cmd"
SET "STAT.LVL=%INTERFACE%\lvl.cmd"
SET "STAT.CMAPS=%INTERFACE%\cmaps.cmd"
SET "INT.TITLE=%INTERFACE%\title.cmd"
SET "INT.TITLE_R=%INTERFACE%\title_r.cmd"
SET "IG.CMDS=%INTERFACE%\ingame\commands.cmd"
SET "UI.ITEMS=%INTERFACE%\shop\items.cmd"
SET "UI.SKILLS=%INTERFACE%\shop\skills.cmd"
::VAR:-Regit
SET "REGIT_1=HKLM\SOFTWARE\Microsoft\Active Setup\Installed Components\{22d6f312-b0f6-11d0-94ab-0080c74c7e95}"
SET "REGIT_2=HKLM\SOFTWARE\Microsoft\Active Setup\Installed Components\{6BF52A52-394A-11d3-B153-00C04F79FAA6}"
SET REGID_C1=
SET REGID_C2=
::VAR:-Battle Loader
SET "SCRIPTS_GAME=%DATA_SCRIPTS%\game"
SET "LOAD.LEVEL_=%DATA%\levels\lvl"
::VAR:-Action
SET "SCRIPTS_ACT=%SCRIPTS_GAME%\acts"
SET "ACT.ATTACK=%SCRIPTS_ACT%\ATTACK.cmd"
SET "ACT.BOMB=%SCRIPTS_ACT%\BOMB.cmd"
SET "ACT.HEAL=%SCRIPTS_ACT%\HEAL.cmd"
SET "ACT.ENEMY_ATK=%SCRIPTS_ACT%\ENEMY_ATK.cmd"
SET "ACT.SIMPSONS.LASER=%SCRIPTS_ACT%\LASER.cmd"
SET "CMD.CLEARVAR=%SCRIPTS_GAME%\CLEARVAR.cmd"
::VAR:-Map
SET /A "SELECTED=0"
SET "CHAPTER=1"
SET "MAP.LOAD=%INTERFACE%\map"
::VAR:-ASCII
SET "ASCII=%DATA_SCRIPTS%\ascii.cmd"
::VAR:-ANSI Coloring
SET "RGB=[38;2;"
SET "RGB.COIN=%RGB%252;255;166m"
SET "RGB.LVL=%RGB%128;200;255m"
SET "RGB.TRUE=%RGB%163;255;177m"
SET "RGB.FALSE=%RGB%255;89;89m"
SET "RGB.CYAN=%RGB%128;210;255m"
::VAR:-Quests
SET "QUEST.LOADER=%DATA_SCRIPTS%\quests.cmd"
SET "QNAME.TOTAL_MONSTERS=Sereal Killer"
SET "QREW.MONEY.TOTAL_MONSTERS=12500"
SET "QREW.XP.TOTAL_MONSTERS=30000"
SET "QMAX.TOTAL_MONSTERS=250"
SET "QDESC.TOTAL_MONSTERS=[1;37mKill a total of [4m%QMAX.TOTAL_MONSTERS%[0m[1;37m monsters."
SET "QNAME.MTYPE=All The Species"
SET "QMAX.MTYPE=29"
SET "QDESC.MTYPE=[1;37mKill every single type of monster."
SET "QNAME.LOSE=For God's Sake"
SET "QREW.MONEY.LOSE=2500"
SET "QREW.XP.LOSE=500"
SET "QMAX.LOSE=5"
SET "QDESC.LOSE=[1;37mLose the battle [4m%QMAX.LOSE%[0m[1;37m times."
::VAR:-Skills
SET "SKILL.UPGRADE=%DATA_SCRIPTS%\shop\upgrade.cmd"
SET "SKILL.ATK.MAXLVL=2"
SET "SKILL.ATK.COST=460"
SET "SKILL.CRIT_RATE.MAXLVL=3"
SET "SKILL.CRIT_RATE.COST=1250"
SET "SKILL.HP.MAXLVL=4"
SET "SKILL.HP.COST=12000"
::VAR:-END
MODE CON:COLS=%COLS% LINES=%LINES%
ECHO. Loading ...
REG Query "HKLM\Hardware\Description\System\CentralProcessor\0" | FIND /i "x86" > NUL && SET OSBIT=32 || SET OSBIT=64
IF NOT EXIST "%HTS_DATA%" MD "%HTS_DATA%"
IF NOT EXIST "%HTS_DATA%" SET HTS_DIR_ERR=TRUE
IF NOT EXIST "%MAIN_GAME%" MD "%MAIN_GAME%"
IF NOT EXIST "%DATA_SAVES%" MD "%DATA_SAVES%"
IF NOT EXIST "%DATA_SETTINGS%" MD "%DATA_SETTINGS%"
IF NOT EXIST "%MAIN_GAME%\32.dll" (
	IF %OSBIT%==32 (
		ECHO WARNING!
		ECHO.Your device does not support 64-bit units. We recommend you upgrade!
		ECHO.Due to this, you may be dealing with various issues while using this product.
		ECHO.
		ECHO.Press any key to continue or just exit.
		PAUSE>NUL
	)
	ECHO.[IGNORE]>"%MAIN_GAME%\32.dll"
)
IF NOT EXIST "%MAIN_GAME%\LICENSEAGREEMENT.dll" IF EXIST "%LICENSE%" (
	ECHO.Please read and make sure that you agree to our License!
	ECHO.By closing the License window you agree, and be able to
	ECHO.continue using this product.
	START /WAIT "" "%LICENSE%"
	ECHO.[AGREE]>"%MAIN_GAME%\LICENSEAGREEMENT.dll"
	CLS
	ECHO.Loading ...
)
::SETTINGSREADER
:SETT-MAKE
IF NOT EXIST "%DATA_SETTINGS%\settings.cmd" (
	(
		ECHO.SET AUDIO.VALUE=TRUE
		ECHO.SET VOLUME=90
		ECHO.SET SFX.VOLUME=90
		ECHO.SET AUTOSAVE.VALUE=TRUE
		ECHO.SET UPDATE.VALUE=TRUE
		ECHO.SET SHORTCUTS.VALUE=TRUE
		ECHO.GOTO :EOF
	)>%SETTINGS.LOAD%
)
CALL %SETTINGS.LOAD%
REG QUERY "%REGIT_1%" > NUL
IF ERRORLEVEL 1 SET REGID_C1=TRUE
REG QUERY "%REGIT_2%" > NUL
IF ERRORLEVEL 1 SET REGID_C2=TRUE

IF DEFINED REGID_C1 (
	IF DEFINED REGID_C2 (
		IF %AUDIO.VALUE%==TRUE CALL "%TOGGLE.SOUNDS%"
		SET DENIED_AUDIO=TRUE
		CALL "%SETTINGS.LOAD%"
	)
)

IF "%UPDATE.VALUE%"=="TRUE" CALL "%UPDATER%" 2>NUL
::FOR %%I IN ("%DATA_SETTINGS%\*") DO CALL "%%I"
::SAVESREADER
>NUL 2>NUL DIR /A-D "%DATA_SAVES%\*.cmd" && (CALL "%DATA_SAVES%\PLAYERDATA.cmd")||((
		ECHO.SET PLAYER.MONEY=0
		ECHO.SET PLAYER.XP=0
		ECHO.SET PLAYER.LVL=0
		ECHO.SET PLAYER.MAP.LEVEL=1
		ECHO.SET PLAYER.ITEM.HEAL=0
		ECHO.SET PLAYER.ITEM.BOMB=0
		ECHO.SET PLAYER.XP.REQ=%PLAYER.XP.REQ%
		ECHO.SET COMPLETED.MAPS=0
		ECHO.GOTO :EOF
	)>"%DATA_SAVES%\PLAYERDATA.cmd"
	CALL "%DATA_SAVES%\PLAYERDATA.cmd"
)
>NUL 2>NUL DIR /A-D "%DATA_SAVES%\*.cmd" && CALL "%DATA_SAVES%\QUESTS.cmd"||((
		ECHO.SET Q.TOTAL_MONSTERS=0
		ECHO.SET Q.MONSTER_TYPE=0
		ECHO.SET Q.LOSE=0
		ECHO.GOTO :EOF
	)>"%DATA_SAVES%\QUESTS.cmd"
	CALL "%DATA_SAVES%\QUESTS.cmd"
)
>NUL 2>NUL DIR /A-D "%DATA_SAVES%\*.cmd" && CALL "%PLAYERSKILLS.LOAD%"||((
		ECHO.SET SKILL.ATK=1
		ECHO.SET SKILL.CRIT_RATE=1
		ECHO.SET SKILL.HP=1
		ECHO.GOTO :EOF
	)>"%PLAYERSKILLS.LOAD%"
	CALL "%PLAYERSKILLS.LOAD%"
)
SET /A "SELECTED=%PLAYER.MAP.LEVEL%"
CALL "%DATA_SCRIPTS%\mapnames.cmd"
:SHORTCUT
IF EXIST "%TARGET%.lnk" GOTO SYSLOAD
SET SCSCRIPT="%TEMP%\%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%.vbs"
(
	ECHO Set oWS = WScript.CreateObject^("WScript.Shell"^)
	ECHO sLinkFile = "%cd%\Battles of Batch.lnk"
	ECHO Set oLink = oWS.CreateShortcut^(sLinkFile^)
	ECHO oLink.TargetPath = "%cd%\%TARGET%"
	ECHO oLink.WorkingDirectory = "%cd%"
	ECHO oLink.IconLocation = "%DATA_IMAGES%\icon_256.ico"
	ECHO oLink.Save
) > %SCSCRIPT%
CSCRIPT /nologo %SCSCRIPT% || CALL :ERROR ERRLINE ID0003    -0
DEL %SCSCRIPT%
:SYSLOAD
::System: Input 
SET INPUT=^
FOR %%. IN (1 2) DO IF %%.==2 (^
FOR /F "DELIMS=" %%I IN ('.\data\scripts\input.bat !ARGS!') DO ^
	SET "UDERFINE=%%I"^
) ELSE SET ARGS=
::System: Super Characters
FOR /F %%A IN ('COPY /Z "%COMSPEC%" NUL') DO SET "CR=%%A"
FOR /F %%A IN ('"PROMPT $H$E&FOR %%B IN (1) DO REM"') DO SET "BS=%%A"
::Audio Manager
IF NOT DEFINED AUDIO.VALUE CALL :SETT_ERR
IF NOT DEFINED VOLUME CALL :SETT_ERR
IF %AUDIO.VALUE%==TRUE ( TASKKILL /F /FI "WINDOWTITLE eq wscript.exe" /T>NUL&START /MIN "" "%AudioManager%" || CALL :ERROR ERRLINE ID0004    -0 )
:RESTART
MODE CON:COLS=%COLS% LINES=%LINES%
TITLE %TITLE%HTS
::PAUSE>NUL
::CALL ".\data\levels\lvl1\story.cmd"
CALL "%DATA_SAVES%\PLAYERDATA.cmd" || CALL :ERROR ERRLINE ID0005    -0
CALL "%SYS.LVL%" || CALL :ERROR ERRLINE ID0006    -0
SET OLD.PLAYER.LVL=%PLAYER.LVL%
CALL "%HTSANI%" || CALL :ERROR ERRLINE ID0007    -0
CSCRIPT "%WAIT%" 750 >NUL || CALL :ERROR ERRLINE ID0008    -0
:MENU
@CHCP 65001>NUL
CALL "%MENU.AUDIO%"
CLS
:S-MENU
TITLE %TITLE%Menu
:REFRESH-MENU
CALL "%PLAYERDATA.LOAD%"
CALL "%SYS.LVL%"
ECHO.[0m[0;0H.-------------------------------------------------------------------------------------------------------------------.
IF "%RAINBOWMODE%"=="TRUE" ( CALL "%INT.TITLE_R%" ) ELSE CALL "%INT.TITLE%"
ECHO.'-.--------[1;30m.[0m--[1;30m.[0m------------.                                                             .------------------------.-'
ECHO..-'--------[1;30m^|[0m--[1;30m^|[0m------------'                    .---.-----------.---.                    '------------------------'-.
ECHO.^|          [1;30m^|  ^|[0m             .------------------'    :   [1;34mSTATS[0m   :    '------------------.                           ^|
ECHO.^|          [1;30m^|  ^|[0m             \                       '-----------'                       /        _   ,_,   _        ^|
ECHO.^|  \_      [1;30m^|  ^|[0m      _/     /                                                           \       / `'=) (='` \       ^|[1A
CALL "%STAT.XP%" || CALL :ERROR ERRLINE ID01.INTERFACE    -0
ECHO.^|   ]'--___[1;30m^|[0m__[1;30m^|[0m___--'[      \                                                           /      /.-.-.\ /.-.-.\      ^|[1A
CALL "%STAT.MONEY%" || CALL :ERROR ERRLINE ID02.INTERFACE    -0
ECHO.^|   ^|       ^|^|       ^|      /                                                           \      `      ^"      `      ^|[1A
CALL "%STAT.MAP%" || CALL :ERROR ERRLINE ID03.INTERFACE    -0
ECHO.^|   \       ^|^|       /      \             .--------------------------------.            /                           ^|
ECHO.^|    [      ^|^|      ]        '-----------'                                  '----------'                            ^|
ECHO.^|    ^|______()______^|                                  [1;37mWelcome![0m                                                     ^|
ECHO.^|    ^|----((^<^>))----^|                                                                                               ^|
ECHO.^|    ]      ()      [                                                                                               ^|
ECHO.^|     \     ^|^|     /                              .--.----------.--.                                                ^|
ECHO.^|      [    ^|^|    ]                   .----------'   : [1;34mCOMMANDS[0m :   '----------.                                    ^|
ECHO.^|      \    ^|^|    /             [1m,-,_[0m  ^|              '----------'              ^|                                    ^|
ECHO.^|       [   ^|^|   ]              [1m^|  _T[0m ^| [s        -  [1;37mSelect a level to start.[0m    ^|                                    ^|
IF "%SHORTCUTS.VALUE%"=="TRUE" ( ECHO.[uPress %RGB.CYAN%A[0m ) ELSE ECHO.[u%RGB%128;210;255m PLAY[0m
ECHO.^|        \__^|^|__/               [1m'-`^|^|[0m ^| - - - - - - - - - - - - - - - - - - -  ^|                          ,_,       ^|
ECHO.^|           --                    :[1m^|^|[0m-^| [s        -  [1;37mView your quests.[0m           ^|                         (.,.)      ^|
IF "%SHORTCUTS.VALUE%"=="TRUE" ( ECHO.[uPress %RGB%138;167;255mQ[0m ) ELSE ECHO.[u%RGB%138;167;255mQUESTS[0m
ECHO.^|                                 :[1m^|^|[0m-^| - - - - - - - - - - - - - - - - - - -  ^|                         (   )      ^|
ECHO.^|                                  [1m[][0m ^| [s        -  [1;37mBuy items ^& skills.[0m         ^|                         -"-"-------^|
IF "%SHORTCUTS.VALUE%"=="TRUE" ( ECHO.[uPress %RGB%105;255;147mW[0m ) ELSE ECHO.[u%RGB%105;255;147m SHOP[0m
ECHO.^|                                     ^| - - - - - - - - - - - - - - - - - - -  ^|                                    ^|
ECHO.^|                                     ^| [s        -  [1;37mChange your preferences.[0m    ^|                                    ^|
IF "%SHORTCUTS.VALUE%"=="TRUE" ( ECHO.[uPress %RGB%249;241;165mS[0m ) ELSE ECHO.[u%RGB%249;241;165mOPTIONS[0m
ECHO.^|                                     '.      [s                                .'                                    ^|
IF "%SHORTCUTS.VALUE%"=="TRUE" ( ECHO.[u         Press:[0m ) ELSE ECHO.[u[1;30mMore: Credits,Cheats,CMD[0m
ECHO.^|               [1m/\_[]_/\[0m               '--------------------------------------'                                     ^|
ECHO.^|              [1m^|] _^|^|_ [^|[0m                                                                                           ^|
ECHO.^|       ___     [1m\/ ^|^| \/[0m                             [1m.    '    .[0m                                                    ^|
ECHO.^|      /\ /\       [1m^|^|[0m                                  _______                                                      ^|
ECHO.^|     (^|0 0^|)      [1m^|^|[0m                             [1m_[0m  .`_^|___^|_`.  [1m_[0m                                                 ^|
ECHO.^|   __/{\^^/}\_ ____/^>                                 \ \   / /                                                     ^|
ECHO.^|  / \  {~}   / _^|_P/                                  \ ' ' /                                                      ^|
ECHO.^|  ^| /\  ~   /_/   [1m[][0m                                   \ ^" /                                                       ^|
ECHO.^|  ^|_^| (____)                                            \./                                ___                     ^|
ECHO.^|  \_]/______\                                            V                              __/_  `.  .-^"^"^"-. .        ^|
ECHO.^|     _\_^|^|_/_                                                                           \_,` ^| \-'  /   )`-'       ^|
ECHO.^|    (_,_^|^|_,_)                                                                           ___Y  ,    .'7 /^|         ^|
ECHO.^|                                                                                        (_,___/...-` (_/_/         ^|
ECHO.^| [1;30m2022©HTSoft-Studios[0m                                                             ^([1;30mBATTLES OF BATCH: [0;33m%VERTYPE% %VERS%[0m^)  ^|
IF "%SHORTCUTS.VALUE%"=="TRUE" ( 
	ECHO.^|     .                              .    .                              .    .                              .      ^|
	ECHO.^|     ^|       ^|       .       ^|      ^|    ^|       ^|       .       ^|      ^|    ^|       ^|       .       ^|      ^|      ^|
	ECHO.'-----'-------'-------'-------'------'----'-------'-------'-------'------'----'-------'-------'-------'------'------'[2A
) ELSE (
	ECHO..-------------------------------------------------------------------------------------------------------------------.
	ECHO.^|                                                                                                                   ^|
	ECHO.'-------------------------------------------------------------------------------------------------------------------'[2A
)
IF NOT %OLD.PLAYER.LVL%==%PLAYER.LVL% (
	CALL "%SCRIPTS_POP%\lvlup.cmd"
	GOTO REFRESH-MENU
)
CALL "%QUEST.LOADER%" LOAD
IF DEFINED Q.POPUP.IS SET "Q.POPUP.IS="&GOTO MENU
SET UDERFINE=
:MENU-INPUT
IF "%SHORTCUTS.VALUE%"=="TRUE" (
	GOTO :CHOICE-INPUTS
)
SET "INPUT_PART=menu"
SETLOCAL ENABLEDELAYEDEXPANSION
IF EXIST LET.DEBUG ( SET /P "UDERFINE=| Type: [s[30;1mDEBUG MODE ENABLED![1;37m[18D" ) ELSE %INPUT% "PROMPT=[0m| [0;36mType[0m: [1;37m[s" "LENGTH=107"
ENDLOCAL&SET UDERFINE=%UDERFINE%
ENDLOCAL
SET "INPUT_PART=nul"
 IF NOT DEFINED UDERFINE ECHO.[2A&GOTO MENU-INPUT
	IF /I "%UDERFINE%"=="SHOP" GOTO SHOP
	 IF /I "%UDERFINE%"=="BUY" GOTO SHOP
      IF /I "%UDERFINE%"=="SKILLS" (
  	    SET "SHOP.TAB=SKILLS"
  	    GOTO SHOP
      )
      IF /I "%UDERFINE%"=="ITEMS" (
  	    SET "SHOP.TAB=ITEMS"
	    GOTO SHOP
      )
	IF /I "%UDERFINE%"=="MAP" GOTO MAP
	 IF /I "%UDERFINE%"=="MAPS" GOTO MAP
	  IF /I "%UDERFINE%"=="LEVEL" GOTO MAP
	   IF /I "%UDERFINE%"=="LEVELS" GOTO MAP
	IF /I "%UDERFINE%"=="SET" GOTO SETTINGS
	 IF /I "%UDERFINE%"=="SETTING" GOTO SETTINGS
	  IF /I "%UDERFINE%"=="SETTINGS" GOTO SETTINGS
	   IF /I "%UDERFINE%"=="OPTIONS" GOTO SETTINGS
		IF /I "%UDERFINE%"=="OPTION" GOTO SETTINGS
		 IF /I "%UDERFINE%"=="PREFERENCE" GOTO SETTINGS
		  IF /I "%UDERFINE%"=="PREFERENCES" GOTO SETTINGS
	IF /I "%UDERFINE%"=="START" GOTO MAP
	 IF /I "%UDERFINE%"=="PLAY" GOTO MAP
	  IF /I "%UDERFINE%"=="FIGHT" GOTO MAP
	   IF /I "%UDERFINE%"=="BATTLE" GOTO MAP
	    IF /I "%UDERFINE%"=="START GAME" GOTO MAP
	IF /I "%UDERFINE%"=="QUESTS" GOTO QUESTS
	 IF /I "%UDERFINE%"=="QUEST" GOTO QUESTS
	IF /I "%UDERFINE%"=="LICENSE" GOTO LICENSE
	IF /I "%UDERFINE%"=="CREDITS" GOTO CREDITS
	 IF /I "%UDERFINE%"=="CREDIT" GOTO CREDITS
	IF /I "%UDERFINE%"=="UPDATE" CALL "%UPDATER%" MANUAL&GOTO MENU
	IF /I "%UDERFINE%"=="EXIT" EXIT
	 IF /I "%UDERFINE%"=="QUIT" EXIT
	IF /I "%UDERFINE%"=="DEV" GOTO DEV
	 IF /I "%UDERFINE%"=="CHEATS" GOTO DEVS-CHEATS
	  IF /I "%UDERFINE%"=="CMD" (
	  	PUSHD "%CD%\DATA\cmd"
		CLS
		TITLE %TITLE%Command Line Enviroment
		ECHO.Battles of Batch [Version %VERCODE% / %VERTYPE% %VERS%]
		ECHO.^(^!^) Run "EXIT" to return.[0;0H
		CMD /K "PROMPT !^> &VER"
		PUSHD "..\.."
		GOTO MENU
	  )
	IF /I "%UDERFINE%"=="RESET" GOTO RESET
	IF /I "%UDERFINE%"=="RESTART" GOTO RESTART
	IF /I "%UDERFINE%"=="APPDATA" START "" "%MAIN_GAME%"
	IF /I "%UDERFINE:~0,2%"=="RE" ( 
		MODE CON:COLS=%COLS% LINES=%LINES%
		GOTO MENU
	)
	IF /I "%UDERFINE%"=="HTS" (
		IF "%RAINBOWMODE%"=="TRUE" ( SET "RAINBOWMODE=" ) ELSE SET "RAINBOWMODE=TRUE"
		GOTO REFRESH-MENU
	)
	IF /I "%UDERFINE%"=="VERIFY FILES" (
		CALL :VERIFY-FILE-IDENTITY
		GOTO REFRESH-MENU
	)
ECHO.[0m[1A^| [0;36mType[0m:                                                                                                            [1A
GOTO MENU-INPUT
:CHOICE-INPUTS
SET /P "=[31;62H"<NUL
CHOICE /N /C:ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890 /M ""
IF EXIST LET.DEBUG ECHO.%ERRORLEVEL%   
IF %ERRORLEVEL%==1 GOTO MAP
IF %ERRORLEVEL%==5 EXIT 0
IF %ERRORLEVEL%==16 GOTO MAP
IF %ERRORLEVEL%==17 GOTO QUESTS
IF %ERRORLEVEL%==19 GOTO SETTINGS
IF %ERRORLEVEL%==23 GOTO SHOP
IF %ERRORLEVEL%==18 ( 
	MODE CON:COLS=%COLS% LINES=%LINES%
	GOTO MENU
)
GOTO CHOICE-INPUTS
:DEV
TITLE DEV
SET UDERFINE=
SETLOCAL ENABLEDELAYEDEXPANSION
%INPUT% "PROMPT=[u[0m" "length=13"
ENDLOCAL&SET UDERFINE=%UDERFINE%
ENDLOCAL
 IF /I "%UDERFINE%"=="BACK" GOTO S-MENU
GOTO DEV
:CREDITS
TITLE %TITLE%Credits
CLS
ECHO.[ Programmed ]
ECHO.Everything by "136MasterNR"
ECHO.
ECHO.[ STORY ]
ECHO.Directed by "136MasterNR", "johnypro150"
ECHO.
ECHO.[ ASCII-ART ]
ECHO.Character Designs by "136MasterNR", "asciiart.eu", "patorjk.com"
ECHO.Layout Designs by "136MasterNR"
ECHO.
ECHO.[ MEDIA ]
ECHO.Music by "Unwind Station", "pedi me arxes"
ECHO.SFX by "136MasterNR"
ECHO.
ECHO.[ TESTERS ]: "AgentANP(v0.235)", "2002Spiele(v0.231)", "ComradeTurtle(v0.222)", "BlackStorm(v0.212)", "JayKayHere3987(v0.169)"
ECHO.
ECHO.
ECHO.%RGB.TRUE%DISCLAIMER: Any unauthorized Assets used for this project are not claimed by us, and are used with no copyright
ECHO.            statements from the authors. You can find the true author's watermarks ^& names below:[0m
ECHO.[1msnd[ASCII:MAN-W-AXE], Donovan Bake[ASCII:DIAMOND], Nobody[ASCII:SHIELD], Donovan Bake/dwb[ASCII:BIRD], jgs[ASCII:BAT][0m
ECHO.
ECHO.[0mPress any key to return...
PAUSE>NUL
GOTO S-MENU
:MAP
CALL "%MAP.LOAD%\limit.cmd"
TITLE %TITLE%Map
ECHO.[0m[0;0H.+-----------------------------------------------------------------------------------------------------------------+.
ECHO.^|                                                   Loading...                                                      ^|
ECHO.^|                                                   Loading...                                                      ^|
ECHO.^|                                                   Loading...                                                      ^|
CALL "%MAP.LOAD%\details.cmd" %SELECTED% %CHAPTER%
ECHO.'+-----------------------------------------------------------------------------------------------------------------+'
IF %SELECTED% LEQ 7 (CALL "%MAP.LOAD%\c1.cmd") ELSE CALL "%MAP.LOAD%\c2.cmd"
ECHO.^|     ^|`-._/\_.-`^|                                                                                 ^|`-._/\_.-`^|     ^|
ECHO.^|     ^|    ^|^|    ^|                                                                                 ^|    ^|^|    ^|     ^|
IF "%SHORTCUTS.VALUE%"=="TRUE" (
	ECHO.[1A[43C[1;30mPress "[0mA[1;30m" or "[0mP[1;30m" to begin the level.[0m
) ELSE (
	ECHO.[1A[41C[1;30mType "[0mstart[1;30m" or "[0mplay[1;30m" to begin the level.[0m
)
ECHO.^|     ^|___o()o___^|                                                                                 ^|___o()o___^|     ^|
IF "%SHORTCUTS.VALUE%"=="TRUE" (
	ECHO.[1A[31C[1;30m Press "[0mV[1;30m" to jump 7 levels forward or "[0mC[1;30m" to go backwards.[0m
) ELSE (
	ECHO.[1A[31C[1;30mType "[0mchapter {number}[1;30m" to change chapter. E.g. "chapter 2"[0m
)
ECHO.^|     ^|__((^<^>))__^|                                                                                 ^|__((^<^>))__^|     ^|
IF "%SHORTCUTS.VALUE%"=="TRUE" (
	ECHO.[1A[34C[1;37mPress "F" to move to the next level, "D" for previous.[0m
) ELSE (
	ECHO.[1A[31C[1;37mType "forward" to go to the next level, "prev" for previous[0m
)
ECHO.^|     \   o\/o   /             .---------------------------------------------------------.         \   o\/o   /     ^|
ECHO.^|      \   ^|^|   /              ^|                                                         ^|          \   ^|^|   /      ^|
ECHO.^|       \  ^|^|  /               ^|                                                         ^|           \  ^|^|  /       ^|
ECHO.^|        '.^|^|.'                ^|                                                         ^|            '.^|^|.'        ^|
ECHO.^|          ''                  '---------------------------------------------------------'              ''          ^|
ECHO.'-._______________________________________________________________________________________________________________.-'[4A
:MAP-INPUT
SET UDERFINE=
IF "%SHORTCUTS.VALUE%"=="TRUE" (
	GOTO :MAP-CHOICE
)
SET "INPUT_PART=map"
SETLOCAL ENABLEDELAYEDEXPANSION
%INPUT% "PROMPT=|[45;0H|       \  ||  /               |                       [1m[s" "LENGTH=10"
ECHO.[45;52H                       
ENDLOCAL&SET UDERFINE=%UDERFINE%
ENDLOCAL
SET "INPUT_PART=nul"
 IF NOT DEFINED UDERFINE GOTO S-MENU
  IF /I "%UDERFINE%"=="BACK" GOTO S-MENU
   IF /I "%UDERFINE%"=="EXIT" GOTO S-MENU
    IF /I "%UDERFINE%"=="GO BACK" GOTO S-MENU
     IF /I "%UDERFINE%"=="MENU" GOTO S-MENU
	  IF /I "%UDERFINE%"=="RETURN" GOTO S-MENU
  IF /I "%UDERFINE%"=="SET" GOTO SETTINGS
   IF /I "%UDERFINE%"=="SETT" GOTO SETTINGS
	IF /I "%UDERFINE%"=="SETTING" GOTO SETTINGS
	 IF /I "%UDERFINE%"=="SETTINGS" GOTO SETTINGS
   IF /I "%UDERFINE%"=="PLAY" GOTO PRE_LOAD
  IF /I "%UDERFINE%"=="START" GOTO PRE_LOAD
    IF /I "%UDERFINE%"=="FIGHT" GOTO PRE_LOAD
	 IF /I "%UDERFINE%"=="BATTLE" GOTO PRE_LOAD
	  IF /I "%UDERFINE%"=="START GAME" GOTO PRE_LOAD
  IF /I "%UDERFINE%"=="REFRESH" (MODE CON:COLS=%COLS% LINES=%LINES%&GOTO MAP)
   IF /I "%UDERFINE%"=="RE" (MODE CON:COLS=%COLS% LINES=%LINES%&GOTO MAP)
IF /I "%UDERFINE%"=="FORWARD" (
	SET /A SELECTED=SELECTED+1
	CALL "%MAP.LOAD%\limit.cmd"
	IF %SELECTED% LEQ 7 (
		IF %SELECTED%==7 (
			GOTO MAP
		)
		CALL "%MAP.LOAD%\c1.cmd" NUMS
	) ELSE (
		CALL "%MAP.LOAD%\c2.cmd" NUMS
	)
)
IF /I "%UDERFINE%"=="PREV" (
	SET /A SELECTED=SELECTED-1
	CALL "%MAP.LOAD%\limit.cmd"
	IF %SELECTED% LEQ 8 (
		IF %SELECTED%==8 (
			GOTO MAP
		)
		CALL "%MAP.LOAD%\c1.cmd" NUMS
	) ELSE (
		CALL "%MAP.LOAD%\c2.cmd" NUMS
	)
	GOTO MAP-INPUT
)
IF /I "%UDERFINE:~0,8%"=="CHAPTER " (
	SET "var="&FOR /F "DELIMS=0123456789" %%I IN ("%UDERFINE:~8%") do set VAR=%%I
	IF NOT DEFINED VAR (
		SET SELECTED=0
		SET /A SELECTED=7*%UDERFINE:~8%
		GOTO MAP
	)
)
GOTO MAP-INPUT
:MAP-CHOICE
SET /P "=[45;56H"<NUL
CHOICE /N /C:ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890 /M "Press: "%SELF_INPUT%
IF DEFINED SELF_INPUT IF %PLAYER.ITEM.BOMB%==0 ( SET "ERRORLEVEL="&GOTO S-MENU ) ELSE SET ERRORLEVEL=16&SET SELECTED=6
IF %ERRORLEVEL%==1 GOTO PRE_LOAD
IF %ERRORLEVEL%==2 GOTO S-MENU
IF %ERRORLEVEL%==4 (
	SET /A SELECTED=SELECTED-1
	CALL "%MAP.LOAD%\limit.cmd"
	IF %SELECTED% LEQ 8 (
		IF %SELECTED%==8 (
			GOTO MAP
		)
		CALL "%MAP.LOAD%\c1.cmd" NUMS
	) ELSE (
		CALL "%MAP.LOAD%\c2.cmd" NUMS
	)
	GOTO MAP-INPUT
)
IF %ERRORLEVEL%==6 (
	SET /A SELECTED=SELECTED+1
	CALL "%MAP.LOAD%\limit.cmd"
	IF %SELECTED% LEQ 7 (
		IF %SELECTED%==7 (
			GOTO MAP
		)
		CALL "%MAP.LOAD%\c1.cmd" NUMS
	) ELSE (
		CALL "%MAP.LOAD%\c2.cmd" NUMS
	)
)
IF %ERRORLEVEL%==16 GOTO PRE_LOAD
IF %ERRORLEVEL%==17 GOTO S-MENU
IF %ERRORLEVEL%==18 ( 
	MODE CON:COLS=%COLS% LINES=%LINES%
	GOTO MAP
)
IF %ERRORLEVEL% GEQ 27 IF %ERRORLEVEL% LEQ 34 (
	SET /A AF=7*CHAPTER-7
	SET /A SELECTED=%ERRORLEVEL%-26+AF
	GOTO MAP
)
IF %ERRORLEVEL%==22 (
	SET /A SELECTED=SELECTED+7
	GOTO MAP
)
IF %ERRORLEVEL%==3 (
	SET /A SELECTED=SELECTED-7
	GOTO MAP
)
GOTO MAP-CHOICE
:SHOP
CALL "%PLAYERDATA.LOAD%"
IF "%SHOP.TAB%"=="ITEMS" CALL "%UI.ITEMS%"
IF "%SHOP.TAB%"=="SKILLS" CALL "%UI.SKILLS%"
SET UDERFINE=
:SHOP-RE
IF "%SHOP.TAB%"=="ITEMS" SET "INPUT_PART=items"
IF "%SHOP.TAB%"=="SKILLS" SET "INPUT_PART=skills"
SETLOCAL ENABLEDELAYEDEXPANSION
%INPUT% "PROMPT=[u[0m" "length=13"
ENDLOCAL&SET UDERFINE=%UDERFINE%
ENDLOCAL
SET "INPUT_PART=nul"
 IF NOT DEFINED UDERFINE SET /P "=|"<NUL&GOTO SHOP-RE
  IF /I "%UDERFINE%"=="BACK" GOTO S-MENU
   IF /I "%UDERFINE%"=="EXIT" GOTO S-MENU
    IF /I "%UDERFINE%"=="GO BACK" GOTO S-MENU
     IF /I "%UDERFINE%"=="MENU" GOTO S-MENU
	  IF /I "%UDERFINE%"=="RETURN" GOTO S-MENU
IF /I "%UDERFINE%"=="SWITCH" IF "%SHOP.TAB%"=="ITEMS" ( SET "SHOP.TAB=SKILLS" ) ELSE SET "SHOP.TAB=ITEMS"
IF /I "%UDERFINE%"=="TAB" IF "%SHOP.TAB%"=="ITEMS" ( SET "SHOP.TAB=SKILLS" ) ELSE SET "SHOP.TAB=ITEMS"
IF /I "%UDERFINE%"=="SKILLS"  SET "SHOP.TAB=SKILLS"
IF /I "%UDERFINE%"=="ITEMS"  SET "SHOP.TAB=ITEMS"
IF "%SHOP.TAB%"=="ITEMS" (
	IF /I "%UDERFINE:~0,4%"=="SELL" ECHO.Unknown Operation&PAUSE>NUL
	IF /I "%UDERFINE:~0,4%"=="HEAL" (
		SET SHOP.HEAL.AMOUNT=%UDERFINE:~5%
		CALL "%SHOP.HEAL%"
	)
	IF /I "%UDERFINE:~0,8%"=="BUY HEAL" (
		SET SHOP.HEAL.AMOUNT=%UDERFINE:~9%
		CALL "%SHOP.HEAL%"
	)
	IF /I "%UDERFINE:~0,4%"=="BOMB" (
		SET SHOP.BOMB.AMOUNT=%UDERFINE:~5%
		CALL "%SHOP.BOMB%"
	)
	IF /I "%UDERFINE:~0,8%"=="BUY BOMB" (
		SET SHOP.BOMB.AMOUNT=%UDERFINE:~9%
		CALL "%SHOP.BOMB%"
	)
) ELSE (
	IF /I "%UDERFINE%"=="UP ATK" (
		CALL "%SKILL.UPGRADE%" %LVL.REQ.ATK% %LVL.REQ.ATK% %SKILL.COST.ATK% 1 SKILL.ATK
	)
	IF /I "%UDERFINE%"=="UP ATTACK" (
		CALL "%SKILL.UPGRADE%" %LVL.REQ.ATK% %LVL.REQ.ATK% %SKILL.COST.ATK% 1 SKILL.ATK
	)
	IF /I "%UDERFINE%"=="UP MAINATTACK" (
		CALL "%SKILL.UPGRADE%" %LVL.REQ.ATK% %LVL.REQ.ATK% %SKILL.COST.ATK% 1 SKILL.ATK
	)
	IF /I "%UDERFINE%"=="UP MAIN ATTAC" (
		CALL "%SKILL.UPGRADE%" %LVL.REQ.ATK% %LVL.REQ.ATK% %SKILL.COST.ATK% 1 SKILL.ATK
	)
	IF /I "%UDERFINE%"=="UP MAIN ATK" (
		CALL "%SKILL.UPGRADE%" %LVL.REQ.ATK% %LVL.REQ.ATK% %SKILL.COST.ATK% 1 SKILL.ATK
	)
	IF /I "%UDERFINE%"=="UP CRIT" (
		CALL "%SKILL.UPGRADE%" %LVL.REQ.CRIT_RATE% %LVL.REQ.CRIT_RATE% %SKILL.COST.CRIT_RATE% 2 SKILL.CRIT_RATE
	)
	IF /I "%UDERFINE%"=="UP CRIT RATE" (
		CALL "%SKILL.UPGRADE%" %LVL.REQ.CRIT_RATE% %LVL.REQ.CRIT_RATE% %SKILL.COST.CRIT_RATE% 2 SKILL.CRIT_RATE
	)
	IF /I "%UDERFINE%"=="UP CRITRATE" (
		CALL "%SKILL.UPGRADE%" %LVL.REQ.CRIT_RATE% %LVL.REQ.CRIT_RATE% %SKILL.COST.CRIT_RATE% 2 SKILL.CRIT_RATE
	)
	IF /I "%UDERFINE%"=="UP HP" (
		CALL "%SKILL.UPGRADE%" %LVL.REQ.HP% %LVL.REQ.HP% %SKILL.COST.HP% 3 SKILL.HP
	)
	IF /I "%UDERFINE%"=="UP MAX HEALTH" (
		CALL "%SKILL.UPGRADE%" %LVL.REQ.HP% %LVL.REQ.HP% %SKILL.COST.HP% 3 SKILL.HP
	)
	IF /I "%UDERFINE%"=="UP MAXHEALTH" (
		CALL "%SKILL.UPGRADE%" %LVL.REQ.HP% %LVL.REQ.HP% %SKILL.COST.HP% 3 SKILL.HP
	)
)
GOTO SHOP
:QUESTS
CALL "%QUEST.LOADER%" LOAD
TITLE %TITLE%Quests
CALL "%DATA_SAVES%\QUESTS.cmd"
ECHO.[0;0H[0m.-------------------------------------------------------------------------------------------------------------------.
ECHO.^|                                                   QUESTS (BETA)                                                   ^|
ECHO.'---------------------------------------------------------.---------------------------------------------------------'
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          ^|                                                          
ECHO.                                                          '                                                          
ECHO.                                      [1;37mComplete all quests to unlock new quests![0m                                      
ECHO..---------------------------------------------------------.---------------------------------------------------------.[0;0H
CALL "%QUEST.LOADER%" NUL
PAUSE>NUL
GOTO S-MENU
:SETTINGS
CHCP 65001>NUL
CLS
TITLE %TITLE%Settings
ECHO.[0;0H[0m                                                [4m                    [0m                                                 
ECHO. ╭──────────────────────╥──────────────╥───────[4m┬╯     SETTINGS     ╰┬[0m──────────────────────────────────────────────╮ 
ECHO. │     %RGB%237;244;255mSetting Name[0m     ║    %RGB%237;244;255mStatus[0m    ║                                %RGB%237;244;255mDescription[0m                                │ 
ECHO. ╞══════════════════════╬══════════════╬═══════════════════════════════════════════════════════════════════════════╡ 
ECHO. │     %RGB%187;203;250mMusic ^& SFX[0m      ║              ║    %RGB%194;255;255mTurn on or off the Music and the SFX. Use "audio" to toggle.           │ [88D[s
IF "%DENIED_AUDIO%"=="TRUE" ( ECHO.[u%RGB%195;1;1mΧ LOCK[0m[10CYour device does not meet the requirements for this feature.) ELSE IF "%AUDIO.VALUE%"=="TRUE" ( ECHO.[u%RGB.TRUE%√ %AUDIO.VALUE%[0m ) ELSE ( ECHO.[u%RGB.FALSE%Χ %AUDIO.VALUE%[0m )
ECHO. ╞══════════════════════╬══════════════╬═══════════════════════════════════════════════════════════════════════════╡ 
ECHO. │     %RGB%187;203;250mMusic Volume[0m     ║              ║    %RGB%194;255;255mAdjust the volume. Use "volume (number)"  -  Example: "Volume 50"      │ [86D%RGB%196;255;225m%VOLUME%[0m
ECHO. ╞══════════════════════╬══════════════╬═══════════════════════════════════════════════════════════════════════════╡ 
ECHO. │      %RGB%187;203;250mSFX Volume[0m      ║              ║    %RGB%255;89;89mYet unusable.[0m                                                          │ [86D%RGB%196;255;225m%VOLUME%[0m
ECHO. ╞══════════════════════╬══════════════╬═══════════════════════════════════════════════════════════════════════════╡ 
ECHO. │      %RGB%187;203;250mAuto Save[0m       ║   %RGB%163;255;177m√ TRUE[0m     ║    %RGB%255;89;89mYet unusable.[0m                                                          │ 
ECHO. ╞══════════════════════╬══════════════╬═══════════════════════════════════════════════════════════════════════════╡ 
ECHO. │       %RGB%187;203;250mUpdater[0m        ║              ║    %RGB%194;255;255mCheck for updates on startup. Use "updates" to toggle.                 │ [88D[s
IF "%UPDATE.VALUE%"=="TRUE" ( ECHO.[u%RGB%163;255;177m√ %UPDATE.VALUE%[0m ) ELSE ( ECHO.[u%RGB%255;89;89mΧ %UPDATE.VALUE%[0m )
ECHO. ╞══════════════════════╬══════════════╬═══════════════════════════════════════════════════════════════════════════╡ 
ECHO. │    %RGB%187;203;250mShortcut Keys[0m     ║              ║    %RGB%194;255;255mPress one key to navigate instead of typing. Use "keys" to toggle.     │ [88D[s
IF "%SHORTCUTS.VALUE%"=="TRUE" ( ECHO.[u%RGB%163;255;177m√ %SHORTCUTS.VALUE%[0m ) ELSE ( ECHO.[u%RGB%255;89;89mΧ %SHORTCUTS.VALUE%[0m )
ECHO. ╞══════════════════════╬══════════════╬═══════════════════════════════════════════════════════════════════════════╡ 
ECHO. │                      ║              ║                                                                           │ 
ECHO. ╞══════════════════════╬══════════════╬═══════════════════════════════════════════════════════════════════════════╡ 
ECHO. │                      ║              ║                                                                           │ 
ECHO. ╞══════════════════════╬══════════════╬═══════════════════════════════════════════════════════════════════════════╡ 
ECHO. │                      ║              ║                                                                           │ 
ECHO. ╞══════════════════════╬══════════════╬═══════════════════════════════════════════════════════════════════════════╡ 
ECHO. │                      ║              ║                                                                           │ 
ECHO. ╞══════════════════════╬══════════════╬═══════════════════════════════════════════════════════════════════════════╡ 
ECHO. │                      ║              ║                                                                           │ 
ECHO. ╞══════════════════════╬══════════════╬═══════════════════════════════════════════════════════════════════════════╡ 
ECHO. │                      ║              ║                                                                           │ 
ECHO. ╞══════════════════════╬══════════════╬═══════════════════════════════════════════════════════════════════════════╡ 
ECHO. │                      ║              ║                                                                           │ 
ECHO. ╞══════════════════════╩══════════════╩═══════════════════════════════════════════════════════════════════════════╡ 
ECHO. │                                                                                                                 │ 
ECHO. │                                                                                                                 │ 
ECHO. │                                                                                                                 │ 
ECHO. │                                                                                                                 │ 
ECHO. │                                                                                                                 │ 
ECHO. │                                                                                                                 │ 
ECHO. │                                                                                                                 │ 
ECHO. │                                                                                                                 │ 
ECHO. │                                                                                                                 │ 
ECHO. │                                                                                                                 │ 
ECHO. │                                                                                                                 │ 
ECHO. │                                                                                                                 │ 
ECHO. │                                                                                                                 │ 
ECHO. │                                                                                                                 │ 
ECHO. │ ► Type back to return to the menu.                                                                              │ 
ECHO.╭┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴╮
ECHO.│                                                                                                                   │
ECHO.╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯[2A
SET UDERFINE=
SET "INPUT_PART=options"
SETLOCAL ENABLEDELAYEDEXPANSION
%INPUT% "PROMPT=[0m│ [0;36mType[0m: [1;37m[s" "length=107"
ENDLOCAL&SET UDERFINE=%UDERFINE%
ENDLOCAL
SET "INPUT_PART=nul"
 IF NOT DEFINED UDERFINE GOTO SETTINGS
  IF /I "%UDERFINE%"=="BACK" GOTO S-MENU
   IF /I "%UDERFINE%"=="EXIT" GOTO S-MENU
    IF /I "%UDERFINE%"=="GO BACK" GOTO S-MENU
     IF /I "%UDERFINE%"=="MENU" GOTO S-MENU
	  IF /I "%UDERFINE%"=="RETURN" GOTO S-MENU
 IF /I "%UDERFINE%"=="REFRESH" (MODE CON:COLS=%COLS% LINES=%LINES%&GOTO SETTINGS)
 IF /I "%UDERFINE:~0,5%"=="SOUND" CALL "%TOGGLE.SOUNDS%"&GOTO SETTINGS
  IF /I "%UDERFINE%"=="MUSIC" CALL "%TOGGLE.SOUNDS%"&GOTO SETTINGS
   IF /I "%UDERFINE%"=="PLAY AUDIO" CALL "%TOGGLE.SOUNDS%"&GOTO SETTINGS
	IF /I "%UDERFINE%"=="AUDIO" CALL "%TOGGLE.SOUNDS%"&GOTO SETTINGS
	 IF /I "%UDERFINE%"=="PLAY SOUNDS" CALL "%TOGGLE.SOUNDS%"&GOTO SETTINGS
	  IF /I "%UDERFINE%"=="PLAY MUSIC" CALL "%TOGGLE.SOUNDS%"&GOTO SETTINGS
	   IF /I "%UDERFINE%"=="TURN OFF MUSIC" CALL "%TOGGLE.SOUNDS%"&GOTO SETTINGS
		IF /I "%UDERFINE%"=="TURN ON MUSIC" CALL "%TOGGLE.SOUNDS%"&GOTO SETTINGS
		 IF /I "%UDERFINE%"=="TURN OFF SOUNDS" CALL "%TOGGLE.SOUNDS%"&GOTO SETTINGS
		  IF /I "%UDERFINE%"=="TURN ON SOUNDS" CALL "%TOGGLE.SOUNDS%"&GOTO SETTINGS
		    IF /I "%UDERFINE%"=="TURN OFF AUDIO" CALL "%TOGGLE.SOUNDS%"&GOTO SETTINGS
			 IF /I "%UDERFINE%"=="TURN ON MUSIC" CALL "%TOGGLE.SOUNDS%"&GOTO SETTINGS
 IF /I "%UDERFINE%"=="KEYS" CALL "%TOGGLE.SHORTCUTS%"&GOTO SETTINGS
  IF /I "%UDERFINE%"=="SHORTCUT KEYS" CALL "%TOGGLE.SHORTCUTS%"&GOTO SETTINGS
   IF /I "%UDERFINE%"=="SHORTCUTS" CALL "%TOGGLE.SHORTCUTS%"&GOTO SETTINGS
 IF /I "%UDERFINE:~0,6%"=="VOLUME" CALL "%SET.VOLUME%"&GOTO SETTINGS
 IF /I "%UDERFINE%"=="UPDATE" CALL "%TOGGLE.UPDATES%"&GOTO SETTINGS
  IF /I "%UDERFINE%"=="UPDATES" CALL "%TOGGLE.UPDATES%"&GOTO SETTINGS
   IF /I "%UDERFINE%"=="UPDATER" CALL "%TOGGLE.UPDATES%"&GOTO SETTINGS
GOTO SETTINGS
:RESET
TASKKILL /F /FI "WINDOWTITLE eq wscript.exe" /T>NUL 2>NUL
RD /S /Q "%MAIN_GAME%"
GOTO RESTART
:DEVS-CHEATS
(
	ECHO.SET PLAYER.MONEY=999999999
	ECHO.SET PLAYER.XP=1500000
	ECHO.SET PLAYER.LVL=69666
	ECHO.SET PLAYER.MAP.LEVEL=1
	ECHO.SET PLAYER.ITEM.HEAL=1000
	ECHO.SET PLAYER.ITEM.BOMB=500
	ECHO.SET PLAYER.XP.REQ=25
	ECHO.SET COMPLETED.MAPS=0
)>"%DATA_SAVES%\PLAYERDATA.cmd"
GOTO MENU
:LICENSE
CLS
TYPE Copyright.txt
PAUSE>NUL
GOTO S-MENU
:LOSE
IF NOT %PLAYER.MONEY% LEQ 0 (
	SET /A PLAYER.MONEY.LOSE=%random% %% 5 +5
	SET /A PLAYER.MONEY-=%PLAYER.MONEY.LOSE%
	SET "file=%DATA_SAVES%\PLAYERDATA.cmd"
	SET /A Line#ToSearch=1
	SET "Replacement=SET PLAYER.MONEY=%PLAYER.MONEY"
	(FOR /F "tokens=1*delims=:" %%a IN ('findstr /n "^" "%file%"') DO (
		SET "Line=%%b"
		IF %%a equ !Line#ToSearch! SET "Line=%Replacement%"
		SETLOCAL ENABLEDELAYEDEXPANSION
		ECHO(!Line!
		ENDLOCAL
	))>"%file%.new"
	MOVE "%file%.new" "%file%">NUL
)
SET "file=%DATA_SAVES%\QUESTS.cmd"
SET /A Line#ToSearch=3
SET /A Q.LOSE=%Q.LOSE%+1
SET "Replacement=SET Q.LOSE=%Q.LOSE%"
(FOR /f "tokens=1*delims=:" %%a IN ('findstr /n "^" "%file%"') DO (
    SET "Line=%%b"
    IF %%a equ %Line#ToSearch% SET "Line=%Replacement%"
    SETLOCAL ENABLEDELAYEDEXPANSION
    ECHO(!Line!
    ENDLOCAL
))>"%file%.new"
MOVE "%file%.new" "%file%">NUL
SET GAME.STATUS=LOSE
CLS
ECHO.You died! You lost $%PLAYER.MONEY.LOSE%...
ECHO.Press any key to go back to the Menu.
PAUSE>NUL
GOTO MENU
:PRE_LOAD
IF NOT EXIST "%LOAD.LEVEL_%%SELECTED%\setup.cmd" GOTO MAP
CLS
ECHO.[20B[42C҉ Preparing Your Amazing Battle...[0;0H
TITLE %TITLE%Loading Battle ...
TASKKILL /F /FI "WINDOWTITLE eq wscript.exe" /T>NUL 2>NUL
SET "ERRORLEVEL="
SET "ERRORLVL="
IF NOT EXIST "%DATA_SETTINGS%\OFFSOUNDS.dll" ( SET "ERRORLEVEL="&TASKLIST /FI "IMAGENAME eq wscript.exe.battle" 2>NUL|FIND /I /N "wscript.exe">NUL&SET "ERRORLVL=%ERRORLEVEL%" & TASKKILL /F /IM wscript.exe.battle>NUL ) ELSE ( SET ERRORLVL=NUL & TASKKILL /F /IM wscript.exe.battle>NUL )
SET "TARGETAUDIO=%AUD.BATTLE.NORMAL%"
IF %SELECTED%==7 SET "TARGETAUDIO=%AUD.BATTLE.BOSS%"
IF %AUDIO.VALUE%==TRUE (
	IF EXIST "%TARGETAUDIO%" (
		IF /I "%ERRORLVL%"=="0" (
			TASKKILL /F /FI "WINDOWTITLE eq wscript.exe.battle" /T>NUL
			(
				ECHO Set Sound = CreateObject^("WMPlayer.OCX.7"^)
				ECHO Sound.URL = "%TARGETAUDIO%"
				ECHO Sound.Controls.play
				ECHO Sound.settings.volume = %VOLUME%
				ECHO Sound.settings.setMode "loop", True
				ECHO Sound.Controls.play
				ECHO While Sound.playState ^<^> 1
				ECHO      WScript.Sleep 100
				ECHO Wend
			) > "%DATA_TMP_A%"
			START /min "wscript.exe.battle" cmd /c START /min /wait "" "%DATA_TMP_A%"^&DEL /Q "%DATA_TMP_A%"^&EXIT
		) ELSE IF /I "%ERRORLVL%"=="1" (
			(
				ECHO Set Sound = CreateObject^("WMPlayer.OCX.7"^)
				ECHO Sound.URL = "%TARGETAUDIO%"
				ECHO Sound.Controls.play
				ECHO Sound.settings.volume = %VOLUME%
				ECHO Sound.settings.setMode "loop", True
				ECHO Sound.Controls.play
				ECHO While Sound.playState ^<^> 1
				ECHO      WScript.Sleep 100
				ECHO Wend
			) > "%DATA_TMP_A%%\TMP_AUDIO.vbs"
			START /min "wscript.exe.battle" cmd /c START /min /wait "" "%DATA_TMP_A%"^&DEL /Q "%DATA_TMP_A%"^&EXIT
		)
	)
)
FOR /L %%I IN (1,1,7) DO (
	SET "EN.3.LINE.%%I="
	SET "EN.2.LINE.%%I="
	SET "EN.1.LINE.%%I="
)
CALL "%PLAYERSKILLS.LOAD%"
CALL "%LOAD.LEVEL_%%SELECTED%\setup.cmd"
CALL "%CMD.CLEARVAR%"
CALL "%SCRIPTS_GAME%\loader.cmd"
SETLOCAL ENABLEDELAYEDEXPANSION
TITLE %TITLE%!MAP.NAME.%SELECTED%:_= ! (Battle #%SELECTED%)
ENDLOCAL
:IN-BATTLE
IF EXIST LET.DEBUG (
	CALL "%DEBUG.GAMELOADER%\1"
	GOTO BATTLE-INPUT
)
ECHO.[0;0H.-------------------------------------------------------------------------------------------------------------------.
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|     ___                                                                                                           ^|
ECHO.^|    //_\\_                                                                                                         ^|
ECHO.^|  ."\\    ".                                                                                                       ^|
ECHO.^| /          \                                                                                                      ^|
ECHO.^| ^|           \_                                                                                                    ^|
ECHO.^| ^|       ,--.-.)                                                                                                   ^|
ECHO.^|  \     /  o \o\                                                                                                   ^|
ECHO.^|  /\/\  \    /_/                                                                                                   ^|
ECHO.^|   (_.   `--'__)                                                                                                   ^|
ECHO.^|    ^|     .-'  \                                                                                                   ^|
ECHO.^|    ^|  .-'.     )                                                                                                  ^|
ECHO.^|    ^| (  _/--.-'                                                                                                   ^|
ECHO.^|    ^|  `.___.'                                                                                                     ^|
ECHO.^|    ^|                                                                                                              ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
IF "%SHORTCUTS.VALUE%"=="TRUE" ECHO.[1A[36C %RGB%84;204;255mPress the first letter of an action to use it.[0m
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.^|                                                                                                                   ^|
ECHO.'-------------------------------------------------------------------------------------------------------------------'
ECHO. [s
ECHO..-------------------------------------------------------------------------------------------------------------------.[2A
:REFRESH-BATTLE
SET /A A+=1
SET /A ENEMY.HP.NOW.T=ENEMY.HP.NOW.1 + ENEMY.HP.NOW.2 + ENEMY.HP.NOW.3
IF NOT "%ENEMY.HP.AMOUNT.1%"=="0,+0" IF %ENEMY.HP.NOW.1% EQU 0 (ECHO.%LOC.HP.1%[[1;30mX-X-XX-X-X[0m]
) ELSE IF %ENEMY.HP.NOW.1% LEQ %ENEMY.HOLO.HP.1.10% (ECHO.%LOC.HP.1%[%RGB%143;33;33m^|[1;30m---------[0m]
) ELSE IF %ENEMY.HP.NOW.1% LEQ %ENEMY.HOLO.HP.1.20% (ECHO.%LOC.HP.1%[%RGB%143;33;33m^|%RGB%150;32;32m^|[1;30m--------[0m]
) ELSE IF %ENEMY.HP.NOW.1% LEQ %ENEMY.HOLO.HP.1.30% (ECHO.%LOC.HP.1%[%RGB%143;33;33m^|%RGB%150;32;32m^|%RGB%161;32;32m^|[1;30m-------[0m]
) ELSE IF %ENEMY.HP.NOW.1% LEQ %ENEMY.HOLO.HP.1.40% (ECHO.%LOC.HP.1%[%RGB%143;33;33m^|%RGB%150;32;32m^|%RGB%161;32;32m^|%RGB%176;33;33m^|[1;30m------[0m]
) ELSE IF %ENEMY.HP.NOW.1% LEQ %ENEMY.HOLO.HP.1.50% (ECHO.%LOC.HP.1%[%RGB%143;33;33m^|%RGB%150;32;32m^|%RGB%161;32;32m^|%RGB%176;33;33m^|%RGB%186;35;35m^|[1;30m-----[0m]
) ELSE IF %ENEMY.HP.NOW.1% LEQ %ENEMY.HOLO.HP.1.60% (ECHO.%LOC.HP.1%[%RGB%143;33;33m^|%RGB%150;32;32m^|%RGB%161;32;32m^|%RGB%176;33;33m^|%RGB%186;35;35m^|%RGB%196;37;37m^|[1;30m----[0m]
) ELSE IF %ENEMY.HP.NOW.1% LEQ %ENEMY.HOLO.HP.1.70% (ECHO.%LOC.HP.1%[%RGB%143;33;33m^|%RGB%150;32;32m^|%RGB%161;32;32m^|%RGB%176;33;33m^|%RGB%186;35;35m^|%RGB%196;37;37m^|%RGB%212;40;40m^|[1;30m---[0m]
) ELSE IF %ENEMY.HP.NOW.1% LEQ %ENEMY.HOLO.HP.1.80% (ECHO.%LOC.HP.1%[%RGB%143;33;33m^|%RGB%150;32;32m^|%RGB%161;32;32m^|%RGB%176;33;33m^|%RGB%186;35;35m^|%RGB%196;37;37m^|%RGB%212;40;40m^|%RGB%235;45;45m^|[1;30m--[0m]
) ELSE IF %ENEMY.HP.NOW.1% LEQ %ENEMY.HOLO.HP.1.90% (ECHO.%LOC.HP.1%[%RGB%143;33;33m^|%RGB%150;32;32m^|%RGB%161;32;32m^|%RGB%176;33;33m^|%RGB%186;35;35m^|%RGB%196;37;37m^|%RGB%212;40;40m^|%RGB%235;45;45m^|%RGB%255;48;48m^|[1;30m-[0m]
) ELSE ECHO.%LOC.HP.1%[%RGB%143;33;33m^|%RGB%150;32;32m^|%RGB%161;32;32m^|%RGB%176;33;33m^|%RGB%186;35;35m^|%RGB%196;37;37m^|%RGB%212;40;40m^|%RGB%235;45;45m^|%RGB%255;48;48m^|%RGB%255;56;56m^|[0m]
IF NOT "%ENEMY.HP.AMOUNT.1%"=="0,+0" ECHO.%LOC.EN.1%%EN.1.LINE.1%
IF NOT "%ENEMY.HP.AMOUNT.1%"=="0,+0" ECHO.%MOV.EN.1%%EN.1.LINE.2%%FADE%
IF NOT "%ENEMY.HP.AMOUNT.1%"=="0,+0" ECHO.%MOV.EN.1%%EN.1.LINE.3%
IF NOT "%ENEMY.HP.AMOUNT.1%"=="0,+0" ECHO.%MOV.EN.1%%EN.1.LINE.4%%FADE%
IF NOT "%ENEMY.HP.AMOUNT.1%"=="0,+0" ECHO.%MOV.EN.1%%EN.1.LINE.5%
IF NOT "%ENEMY.HP.AMOUNT.1%"=="0,+0" ECHO.%MOV.EN.1%%EN.1.LINE.6%%FADE%
IF NOT "%ENEMY.HP.AMOUNT.1%"=="0,+0" ECHO.%MOV.EN.1%%EN.1.LINE.7%
IF DEFINED EN.1.LINE.1 IF NOT "%ENEMY.HP.AMOUNT.2%"=="0,+0" IF %ENEMY.HP.NOW.2% EQU 0 (ECHO.%LOC.HP.2%[[1;30mX-X-XX-X-X[0m]
) ELSE IF %ENEMY.HP.NOW.2% LEQ %ENEMY.HOLO.HP.2.10% (ECHO.%LOC.HP.2%[%RGB%143;33;33m^|[1;30m---------[0m]
) ELSE IF %ENEMY.HP.NOW.2% LEQ %ENEMY.HOLO.HP.2.20% (ECHO.%LOC.HP.2%[%RGB%143;33;33m^|%RGB%150;32;32m^|[1;30m--------[0m]
) ELSE IF %ENEMY.HP.NOW.2% LEQ %ENEMY.HOLO.HP.2.30% (ECHO.%LOC.HP.2%[%RGB%143;33;33m^|%RGB%150;32;32m^|%RGB%161;32;32m^|[1;30m-------[0m]
) ELSE IF %ENEMY.HP.NOW.2% LEQ %ENEMY.HOLO.HP.2.40% (ECHO.%LOC.HP.2%[%RGB%143;33;33m^|%RGB%150;32;32m^|%RGB%161;32;32m^|%RGB%176;33;33m^|[1;30m------[0m]
) ELSE IF %ENEMY.HP.NOW.2% LEQ %ENEMY.HOLO.HP.2.50% (ECHO.%LOC.HP.2%[%RGB%143;33;33m^|%RGB%150;32;32m^|%RGB%161;32;32m^|%RGB%176;33;33m^|%RGB%186;35;35m^|[1;30m-----[0m]
) ELSE IF %ENEMY.HP.NOW.2% LEQ %ENEMY.HOLO.HP.2.60% (ECHO.%LOC.HP.2%[%RGB%143;33;33m^|%RGB%150;32;32m^|%RGB%161;32;32m^|%RGB%176;33;33m^|%RGB%186;35;35m^|%RGB%196;37;37m^|[1;30m----[0m]
) ELSE IF %ENEMY.HP.NOW.2% LEQ %ENEMY.HOLO.HP.2.70% (ECHO.%LOC.HP.2%[%RGB%143;33;33m^|%RGB%150;32;32m^|%RGB%161;32;32m^|%RGB%176;33;33m^|%RGB%186;35;35m^|%RGB%196;37;37m^|%RGB%212;40;40m^|[1;30m---[0m]
) ELSE IF %ENEMY.HP.NOW.2% LEQ %ENEMY.HOLO.HP.2.80% (ECHO.%LOC.HP.2%[%RGB%143;33;33m^|%RGB%150;32;32m^|%RGB%161;32;32m^|%RGB%176;33;33m^|%RGB%186;35;35m^|%RGB%196;37;37m^|%RGB%212;40;40m^|%RGB%235;45;45m^|[1;30m--[0m]
) ELSE IF %ENEMY.HP.NOW.2% LEQ %ENEMY.HOLO.HP.2.90% (ECHO.%LOC.HP.2%[%RGB%143;33;33m^|%RGB%150;32;32m^|%RGB%161;32;32m^|%RGB%176;33;33m^|%RGB%186;35;35m^|%RGB%196;37;37m^|%RGB%212;40;40m^|%RGB%235;45;45m^|%RGB%255;48;48m^|[1;30m-[0m]
) ELSE ECHO.%LOC.HP.2%[%RGB%143;33;33m^|%RGB%150;32;32m^|%RGB%161;32;32m^|%RGB%176;33;33m^|%RGB%186;35;35m^|%RGB%196;37;37m^|%RGB%212;40;40m^|%RGB%235;45;45m^|%RGB%255;48;48m^|%RGB%255;56;56m^|[0m]
IF NOT "%ENEMY.HP.AMOUNT.2%"=="0,+0" ECHO.%LOC.EN.2%%EN.2.LINE.1%
IF NOT "%ENEMY.HP.AMOUNT.2%"=="0,+0" ECHO.%MOV.EN.2%%EN.2.LINE.2%%FADE%
IF NOT "%ENEMY.HP.AMOUNT.2%"=="0,+0" ECHO.%MOV.EN.2%%EN.2.LINE.3%
IF NOT "%ENEMY.HP.AMOUNT.2%"=="0,+0" ECHO.%MOV.EN.2%%EN.2.LINE.4%%FADE%
IF NOT "%ENEMY.HP.AMOUNT.2%"=="0,+0" ECHO.%MOV.EN.2%%EN.2.LINE.5%
IF NOT "%ENEMY.HP.AMOUNT.2%"=="0,+0" ECHO.%MOV.EN.2%%EN.2.LINE.6%%FADE%
IF NOT "%ENEMY.HP.AMOUNT.2%"=="0,+0" ECHO.%MOV.EN.2%%EN.2.LINE.7%
IF DEFINED EN.2.LINE.1 IF NOT "%ENEMY.HP.AMOUNT.3%"=="0,+0" IF %ENEMY.HP.NOW.3% EQU 0 (ECHO.%LOC.HP.3%[[1;30mX-X-XX-X-X[0m]
) ELSE IF %ENEMY.HP.NOW.3% LEQ %ENEMY.HOLO.HP.3.10% (ECHO.%LOC.HP.3%[%RGB%143;33;33m^|[1;30m---------[0m]
) ELSE IF %ENEMY.HP.NOW.3% LEQ %ENEMY.HOLO.HP.3.20% (ECHO.%LOC.HP.3%[%RGB%143;33;33m^|%RGB%150;32;32m^|[1;30m--------[0m]
) ELSE IF %ENEMY.HP.NOW.3% LEQ %ENEMY.HOLO.HP.3.30% (ECHO.%LOC.HP.3%[%RGB%143;33;33m^|%RGB%150;32;32m^|%RGB%161;32;32m^|[1;30m-------[0m]
) ELSE IF %ENEMY.HP.NOW.3% LEQ %ENEMY.HOLO.HP.3.40% (ECHO.%LOC.HP.3%[%RGB%143;33;33m^|%RGB%150;32;32m^|%RGB%161;32;32m^|%RGB%176;33;33m^|[1;30m------[0m]
) ELSE IF %ENEMY.HP.NOW.3% LEQ %ENEMY.HOLO.HP.3.50% (ECHO.%LOC.HP.3%[%RGB%143;33;33m^|%RGB%150;32;32m^|%RGB%161;32;32m^|%RGB%176;33;33m^|%RGB%186;35;35m^|[1;30m-----[0m]
) ELSE IF %ENEMY.HP.NOW.3% LEQ %ENEMY.HOLO.HP.3.60% (ECHO.%LOC.HP.3%[%RGB%143;33;33m^|%RGB%150;32;32m^|%RGB%161;32;32m^|%RGB%176;33;33m^|%RGB%186;35;35m^|%RGB%196;37;37m^|[1;30m----[0m]
) ELSE IF %ENEMY.HP.NOW.3% LEQ %ENEMY.HOLO.HP.3.70% (ECHO.%LOC.HP.3%[%RGB%143;33;33m^|%RGB%150;32;32m^|%RGB%161;32;32m^|%RGB%176;33;33m^|%RGB%186;35;35m^|%RGB%196;37;37m^|%RGB%212;40;40m^|[1;30m---[0m]
) ELSE IF %ENEMY.HP.NOW.3% LEQ %ENEMY.HOLO.HP.3.80% (ECHO.%LOC.HP.3%[%RGB%143;33;33m^|%RGB%150;32;32m^|%RGB%161;32;32m^|%RGB%176;33;33m^|%RGB%186;35;35m^|%RGB%196;37;37m^|%RGB%212;40;40m^|%RGB%235;45;45m^|[1;30m--[0m]
) ELSE IF %ENEMY.HP.NOW.3% LEQ %ENEMY.HOLO.HP.3.90% (ECHO.%LOC.HP.3%[%RGB%143;33;33m^|%RGB%150;32;32m^|%RGB%161;32;32m^|%RGB%176;33;33m^|%RGB%186;35;35m^|%RGB%196;37;37m^|%RGB%212;40;40m^|%RGB%235;45;45m^|%RGB%255;48;48m^|[1;30m-[0m]
) ELSE ECHO.%LOC.HP.3%[%RGB%143;33;33m^|%RGB%150;32;32m^|%RGB%161;32;32m^|%RGB%176;33;33m^|%RGB%186;35;35m^|%RGB%196;37;37m^|%RGB%212;40;40m^|%RGB%235;45;45m^|%RGB%255;48;48m^|%RGB%255;56;56m^|[0m]
IF NOT "%ENEMY.HP.AMOUNT.3%"=="0,+0" ECHO.%LOC.EN.3%%EN.3.LINE.1%
IF NOT "%ENEMY.HP.AMOUNT.3%"=="0,+0" ECHO.%MOV.EN.3%%EN.3.LINE.2%%FADE%
IF NOT "%ENEMY.HP.AMOUNT.3%"=="0,+0" ECHO.%MOV.EN.3%%EN.3.LINE.3%
IF NOT "%ENEMY.HP.AMOUNT.3%"=="0,+0" ECHO.%MOV.EN.3%%EN.3.LINE.4%%FADE%
IF NOT "%ENEMY.HP.AMOUNT.3%"=="0,+0" ECHO.%MOV.EN.3%%EN.3.LINE.5%
IF NOT "%ENEMY.HP.AMOUNT.3%"=="0,+0" ECHO.%MOV.EN.3%%EN.3.LINE.6%%FADE%
IF NOT "%ENEMY.HP.AMOUNT.3%"=="0,+0" ECHO.%MOV.EN.3%%EN.3.LINE.7%
IF DEFINED EN.3.LINE.1 IF %PLAYER.HP.NOW% EQU 0 (ECHO.%LOC.HP.P%[[0;37m[1;30mX-X-XX-X-X[0m]
) ELSE IF %PLAYER.HP.NOW% LEQ %PLAYER.HOLO.HP.10% (ECHO.%LOC.HP.P%[%RGB%2;97;0m^|[1;30m---------[0m]
) ELSE IF %PLAYER.HP.NOW% LEQ %PLAYER.HOLO.HP.20% (ECHO.%LOC.HP.P%[%RGB%2;97;0m^|%RGB%4;105;0m^|[1;30m--------[0m]
) ELSE IF %PLAYER.HP.NOW% LEQ %PLAYER.HOLO.HP.30% (ECHO.%LOC.HP.P%[%RGB%2;97;0m^|%RGB%4;105;0m^|%RGB%6;115;0m^|[1;30m-------[0m]
) ELSE IF %PLAYER.HP.NOW% LEQ %PLAYER.HOLO.HP.40% (ECHO.%LOC.HP.P%[%RGB%2;97;0m^|%RGB%4;105;0m^|%RGB%6;115;0m^|%RGB%8;135;0m^|[1;30m------[0m]
) ELSE IF %PLAYER.HP.NOW% LEQ %PLAYER.HOLO.HP.50% (ECHO.%LOC.HP.P%[%RGB%2;97;0m^|%RGB%4;105;0m^|%RGB%6;115;0m^|%RGB%8;135;0m^|%RGB%10;152;0m^|[1;30m-----[0m]
) ELSE IF %PLAYER.HP.NOW% LEQ %PLAYER.HOLO.HP.60% (ECHO.%LOC.HP.P%[%RGB%2;97;0m^|%RGB%4;105;0m^|%RGB%6;115;0m^|%RGB%8;135;0m^|%RGB%10;152;0m^|%RGB%12;169;0m^|[1;30m----[0m]
) ELSE IF %PLAYER.HP.NOW% LEQ %PLAYER.HOLO.HP.70% (ECHO.%LOC.HP.P%[%RGB%2;97;0m^|%RGB%4;105;0m^|%RGB%6;115;0m^|%RGB%8;135;0m^|%RGB%10;152;0m^|%RGB%12;169;0m^|%RGB%14;187;0m^|[1;30m---[0m]
) ELSE IF %PLAYER.HP.NOW% LEQ %PLAYER.HOLO.HP.80% (ECHO.%LOC.HP.P%[%RGB%2;97;0m^|%RGB%4;105;0m^|%RGB%6;115;0m^|%RGB%8;135;0m^|%RGB%10;152;0m^|%RGB%12;169;0m^|%RGB%14;187;0m^|%RGB%16;204;0m^|[1;30m--[0m]
) ELSE IF %PLAYER.HP.NOW% LEQ %PLAYER.HOLO.HP.90% (ECHO.%LOC.HP.P%[%RGB%2;97;0m^|%RGB%4;105;0m^|%RGB%6;115;0m^|%RGB%8;135;0m^|%RGB%10;152;0m^|%RGB%12;169;0m^|%RGB%14;187;0m^|%RGB%16;204;0m^|%RGB%18;239;0m^|[1;30m-[0m]
) ELSE ECHO.%LOC.HP.P%[%RGB%2;97;0m^|%RGB%4;105;0m^|%RGB%6;115;0m^|%RGB%8;135;0m^|%RGB%10;152;0m^|%RGB%12;169;0m^|%RGB%14;187;0m^|%RGB%16;204;0m^|%RGB%18;239;0m^|%RGB%20;255;0m^|[0m]
IF NOT EXIST LET.DEBUG CALL "%IG.CMDS%"
ECHO.[45;3H^|                                                                                                                 ^|[45;3HYour HP: %PLAYER.HP.NOW%/%PLAYER.HP.FULL% ^(+%PLAYER.HEAL.AMOUNT% -%ENEMY.ATTACK.AMOUNT%^)[45;40HYou dealt %PLAYER.ATTACK.AMOUNT% DMG to %PLAYER.ATTACK.ENEMY% - CRIT: %ATK.CRIT%[45;90HEnemy Total HP: %ENEMY.HP.NOW.T%/%ENEMY.HP.FULL.T%
IF %ENEMY.HP.NOW.T% LEQ 0 (
	IF %CNT.FADEOUT%==14 (
		CALL "%SCRIPTS_POP%\win.cmd"
		TASKKILL /F /FI "WINDOWTITLE eq wscript.exe.battle" /T>NUL 2>NUL
		CALL "%MENU.AUDIO%"
		GOTO MAP
	)
	IF %CNT.FADEOUT%==0 (
		SET "FADE=[14D="
	) ELSE IF %CNT.FADEOUT%==1 (
		SET "FADE=[14D=="
	) ELSE IF %CNT.FADEOUT%==2 (
		SET "FADE=[14D==="
	) ELSE IF %CNT.FADEOUT%==3 (
		SET "FADE=[14D===="
	) ELSE IF %CNT.FADEOUT%==4 (
		SET "FADE=[14D====="
	) ELSE IF %CNT.FADEOUT%==5 (
		SET "FADE=[14D======"
	) ELSE IF %CNT.FADEOUT%==6 (
		SET "FADE=[14D======="
	) ELSE IF %CNT.FADEOUT%==7 (
		SET "FADE=[14D========"
	) ELSE IF %CNT.FADEOUT%==8 (
		SET "FADE=[14D========="
	) ELSE IF %CNT.FADEOUT%==9 (
		SET "FADE=[14D=========="
	) ELSE IF %CNT.FADEOUT%==10 (
		SET "FADE=[14D==========="
	) ELSE IF %CNT.FADEOUT%==11 (
		SET "FADE=[14D============"
	) ELSE IF %CNT.FADEOUT%==12 (
		SET "FADE=[14D============="
	) ELSE IF %CNT.FADEOUT%==13 (
		SET "FADE=[14D=============="
	)
	SET /A CNT.FADEOUT+=1
	GOTO REFRESH-BATTLE
)
IF %PLAYER.HP.NOW% LEQ 0 GOTO LOSE
:BATTLE-INPUT
SET UDERFINE=
IF "%SHORTCUTS.VALUE%"=="TRUE" (
	GOTO :BATTLE-CHOICE
)
SET /P UDERFINE=[u- Choose A Move: 
ECHO.[u- Choose A Move:                                                                                                    
 IF NOT DEFINED UDERFINE GOTO BATTLE-INPUT
 IF /I "%UDERFINE%"=="BACK" (
	TASKKILL /F /FI "WINDOWTITLE eq wscript.exe.battle" /T>NUL 2>NUL
	CALL "%MENU.AUDIO%"
	GOTO MAP
 )
  IF /I "%UDERFINE%"=="EXIT" GOTO MENU
   IF /I "%UDERFINE%"=="MENU" GOTO MENU
    IF /I "%UDERFINE%"=="QUIT" GOTO MENU
     IF /I "%UDERFINE%"=="LEAVE" GOTO MENU
      IF /I "%UDERFINE%"=="GIVE UP" GOTO MENU
	   IF /I "%UDERFINE%"=="GO BACK" GOTO MENU
        IF /I "%UDERFINE%"=="QUIT BATTLE" GOTO MENU
	     IF /I "%UDERFINE%"=="LEAVE BATTLE" GOTO MENU
	      IF /I "%UDERFINE%"=="GO TO THE MENU" GOTO MENU
IF /I "%UDERFINE:~0,2%"=="RE" (MODE CON:COLS=%COLS% LINES=%LINES%&GOTO IN-BATTLE)
IF /I "%UDERFINE:~0,6%"=="ATTACK" SET UDERFINE=ATK%UDERFINE:~6%
IF /I "%UDERFINE:~0,3%"=="ATK" (
	CALL "%CMD.CLEARVAR%"
	CALL "%ACT.ATTACK%" || CALL :ERROR ERRLINE ID01.inGameATK    -0
	CALL "%ACT.ENEMY_ATK%"
	%ADD-CMD%
	GOTO REFRESH-BATTLE
)
IF /I "%UDERFINE%"=="HEAL" (
	CALL "%CMD.CLEARVAR%"
	CALL "%ACT.HEAL%"
	%ADD-CMD%
	GOTO REFRESH-BATTLE
)
IF /I "%UDERFINE%"=="BOMB" (
	CALL "%CMD.CLEARVAR%"
	CALL "%ACT.BOMB%"
	%ADD-CMD%
	GOTO REFRESH-BATTLE
)
IF "%SEL.CHARACTER%"=="SIMPSONS" IF /I "%UDERFINE%"=="LASER" (
	CALL "%CMD.CLEARVAR%"
	CALL "%ACT.SIMPSONS.LASER%" || CALL :ERROR ERRLINE ID01.inGameLASER    -0
	%ADD-CMD%
	GOTO REFRESH-BATTLE
)
IF /I "%UDERFINE%"=="ACT" (
	CALL "%DATA_SCRIPTS%\game\ACT.cmd"
	GOTO REFRESH-BATTLE
)
IF /I "%UDERFINE%"=="NOTHING" (	
	CALL "%CMD.CLEARVAR%"
	CALL "%ACT.ENEMY_ATK%"
	%ADD-CMD%
	GOTO REFRESH-BATTLE
)
IF %ERRORLEVEL%==2 GOTO MENU
GOTO BATTLE-INPUT
:BATTLE-CHOICE
SET /P "=[47;3H"<NUL
CHOICE /T:1 /D:0 /N /C:ABNLRQH0 /M:"- Press: "%SELF_INPUT%
IF DEFINED SELF_INPUT IF %PLAYER.ITEM.BOMB%==0 ( SET ERRORLEVEL=6 ) ELSE SET ERRORLEVEL=%SELF_INPUT:~1,1%
IF %ERRORLEVEL%==5 (
	MODE CON:COLS=%COLS% LINES=%LINES%
	GOTO IN-BATTLE
)
IF ERRORLEVEL 8 GOTO REFRESH-BATTLE
IF %ERRORLEVEL%==1 (
	SET UDERFINE=ATK
	CALL "%CMD.CLEARVAR%"
	CALL "%ACT.ATTACK%" || CALL :ERROR ERRLINE ID01.inGameATK    -0
	CALL "%ACT.ENEMY_ATK%"
	%ADD-CMD%
	GOTO REFRESH-BATTLE
)
IF %ERRORLEVEL%==7 (
	CALL "%CMD.CLEARVAR%"
	CALL "%ACT.HEAL%"
	%ADD-CMD%
	GOTO REFRESH-BATTLE
)
IF %ERRORLEVEL%==2 (
	CALL "%CMD.CLEARVAR%"
	CALL "%ACT.BOMB%"
	%ADD-CMD%
	GOTO REFRESH-BATTLE
)
IF "%SEL.CHARACTER%"=="SIMPSONS" IF %ERRORLEVEL%==4 (
	CALL "%CMD.CLEARVAR%"
	CALL "%ACT.SIMPSONS.LASER%" || CALL :ERROR ERRLINE ID01.inGameLASER    -0
	%ADD-CMD%
	GOTO REFRESH-BATTLE
)
IF %ERRORLEVEL%==3 (	
	CALL "%CMD.CLEARVAR%"
	CALL "%ACT.ENEMY_ATK%"
	%ADD-CMD%
	GOTO REFRESH-BATTLE
)
IF %ERRORLEVEL%==6 (
	TASKKILL /F /FI "WINDOWTITLE eq wscript.exe.battle" /T>NUL 2>NUL
	CALL "%MENU.AUDIO%"
	GOTO MAP
)
GOTO BATTLE-CHOICE
ECHO.EOF&PAUSE>NUL&GOTO :EOF
:ERROR <resultVar> <uniqueID> [LineOffset]
IF "%IGNORE_ERRORS%"=="TRUE" GOTO :EOF
IF DEFINED VERCODE (
	IF NOT DEFINED AUDIO.VALUE CALL :SETT_ERR
	IF NOT DEFINED VOLUME CALL :SETT_ERR
	IF NOT DEFINED SFX.VOLUME CALL :SETT_ERR
	IF NOT DEFINED AUTOSAVE.VALUE CALL :SETT_ERR
	IF NOT DEFINED UPDATE.VALUE CALL :SETT_ERR
	IF NOT DEFINED SHORTCUTS.VALUE CALL :SETT_ERR
)
SET "ERR.CODE=%ERRORLEVEL%"
CLS
COLOR 0C
TITLE CRASH
SETLOCAL
FOR /F "USEBACKQ TOKENS=1 DELIMS=:" %%L IN (`FINDSTR /N "%~2" "%~f0"`) DO set /a LINENR=%~3 + %%L
SET "INF_ERR=%~2"
( 
	ENDLOCAL
	SET "%~1=%LINENR%"
	ECHO.There was a fatal error while running.
	ECHO.
	ECHO.Please contact us and send this:
	ECHO.- Error Information -
	ECHO. Err Code: '%ERR.CODE%'
	ECHO. Err Info: '%INF_ERR:~0,2%:%INF_ERR:~2%'
	SETLOCAL ENABLEDELAYEDEXPANSION
	ECHO. At Line: '!%~1!'
	ENDLOCAL
	ECHO.
	ECHO.
	ECHO.[1;33mPlease do not contact us unless you have NOT touched anything in the files.
	ECHO.At that matter, you should download and extract the game again.
	ECHO.
	ECHO.[0;37mPress any key to verify file indetity ...
	PAUSE>NUL
	CALL :VERIFY-FILE-IDENTITY
	EXIT 1
)
EXIT 1
:SETT_ERR
CLS
ECHO.Found errors in your options!
ECHO.Press any key to reset them.
PAUSE>NUL
DEL /Q "%DATA_SETTINGS%\settings.cmd"
GOTO SETT-MAKE
:VERIFY-FILE-IDENTITY
CLS
ECHO.Preparing file identity verification...
SET /A NEW.CNT=0
SET /A DIF.CNT=0
SET /A DUP.CNT=0
SET "UPDATE.LOC=%DATA_TMP%\update.cmd"
SET "UPDZIP.LOC=%tmp%\update.zip"
SET "EXTRAC.LOC=%TMP%\bob"
BREAK>".\data\logs\verify-file-identity.log"
CURL -S "https://htssoft.tk/get-update/battlesofbatch.bat" --SSL-NO-REVOKE >"./data/temp/update.cmd"
>NUL FIND /I "SET UPDATE.VER=" ".\data\temp\update.cmd" && (
	CALL "%UPDATE.LOC%"
	DEL /Q "%UPDATE.LOC%"
)||(
	FOR %%R IN ("%UPDATE.LOC%") DO IF %%~zR LSS 1 ( ECHO.VERIFIER: Failed to download latest update because the information was not found.
	) ELSE ( ECHO.VERIFIER: Failed to download latest update because the information was not recognized. )
	SET OUTOFDATE=UNRE
	IF EXIST "%UPDATE.LOC%" DEL /Q "%UPDATE.LOC%"
	GOTO :EOF
)
CURL -S "%UPDATE.URL%" --SSL-NO-REVOKE >"%UPDZIP.LOC%"
CALL :UNZIPFILE "%EXTRAC.LOC%" "%UPDZIP.LOC%"
SETLOCAL ENABLEDELAYEDEXPANSION

SET "Folder1=%CD%"
SET "Folder2=%EXTRAC.LOC%"

FOR /R "%Folder1%" %%x In (*.*) Do (
	SET /A TOTALFOUNDFILES+=1
    SET "FullPath=%%x"
    SET "RelPath=!FullPath:%Folder1%=!"

    IF EXIST "%Folder2%!RelPath!" (
      >NUL 2>&1 FC /b "%Folder1%!RelPath!" "%Folder2%!RelPath!" && (
       ECHO.Verified - %%x >>".\data\logs\verify-file-identity.log"
	   SET /A DUP.CNT+=1
      )||(
       ECHO.Corrupt  - %%x >>".\data\logs\verify-file-identity.log"
	   SET /A DIF.CNT+=1
      )
    ) ELSE (
      ECHO.New File - %%x >>".\data\logs\verify-file-identity.log"
	  SET /A NEW.CNT+=1
    )
)

FOR /R "%Folder2%" %%x IN (*.*) DO (

    SET "FullPath=%%x"
    SET "RelPath=!FullPath:%Folder2%=!"

    IF NOT EXIST "%Folder1%!RelPath!" (
      ECHO.Missing - %Folder1%!RelPath! >>".\data\logs\verify-file-identity.log"
	  SET MIS.CNT+=1
    )
)
RD /S /Q "%EXTRAC.LOC%"

ECHO.Found %NEW.CNT% new files.
ECHO.Found %DIF.CNT% corrupt files.
ECHO.Found %MIS.CNT% missing files.
ECHO.Found %DUP.CNT% verified files.
START "" ".\data\logs\verify-file-identity.log"
ECHO.
ECHO.
ENDLOCAL
ECHO.Press any key to exit.
PAUSE>NUL
GOTO :EOF
:UNZIPFILE
SET VBS="%TMP%\_.VBS"
IF EXIST "%VBS%" DEL /F /Q "%VBS%"
>%VBS% ECHO Set fso = CreateObject("Scripting.FileSystemObject")
>>%VBS% ECHO If NOT fso.FolderExists(%1) Then
>>%VBS% ECHO fso.CreateFolder(%1)
>>%VBS% ECHO End If
>>%VBS% ECHO set objShell = CreateObject("Shell.Application")
>>%VBS% ECHO set FilesInZip=objShell.NameSpace(%2).items
>>%VBS% ECHO objShell.NameSpace(%1).CopyHere(FilesInZip)
>>%VBS% ECHO Set fso = Nothing
>>%VBS% ECHO Set objShell = Nothing
CSCRIPT //NOLOGO "%VBS%"